README.md - Add TOC and "Enable mgr dashboard" section
ceph/cn pull request #106
Opened 2019-02-14 00:34 UTC by guymguym

2019-02-17 09:00 UTC, guymguym commented
Hey @leseb,
Let me know if anything is missing here for merging it.
Regards

2019-02-18 15:03 UTC, leseb commented
@guymguym oops sorry. Well the thing that bugs me is the rebuilding of the image itself, making changes in the image and then re-using it. To me, this sounds more like a workaround to something that should be fixed inside the container image from the get go.

So I'd be in favor of highlighting this as a temporarly fix, thanks.

2019-02-18 20:10 UTC, guymguym commented
I agree, I would also expect it to work without workarounds.

2019-02-18 21:11 UTC, leseb requested changes

2019-02-18 21:11 UTC, leseb commented on README.md
> +## Enable mgr dashboard
Please mark this as a temporary hack.

2019-02-19 07:06 UTC, guymguym commented on README.md
> +## Enable mgr dashboard
done

2019-02-19 09:28 UTC, leseb approved these changes

2019-02-19 09:34 UTC, merged