Cn downstream
ceph/cn pull request #92
Opened 2018-11-03 11:37 UTC by leseb

2018-11-03 22:58 UTC, ErwanAliasr1 requested changes

2018-11-03 22:58 UTC, ErwanAliasr1 commented on cmd/cluster.go
> + * Ceph Nano (C) 2017 Red Hat, Inc.
2018 :)

2018-11-03 22:58 UTC, ErwanAliasr1 commented on cmd/image.go
> + * Ceph Nano (C) 2017 Red Hat, Inc.
Ditto

2018-11-03 22:58 UTC, ErwanAliasr1 commented on cmd/image_list.go
> + * Ceph Nano (C) 2017 Red Hat, Inc.
Ditto.

2018-11-03 22:58 UTC, ErwanAliasr1 commented on cmd/image_update.go
> + * Ceph Nano (C) 2017 Red Hat, Inc.
Ditto

2018-11-03 22:58 UTC, ErwanAliasr1 commented on cmd/kube.go
> + * Ceph Nano (C) 2017 Red Hat, Inc.
etc... ;)

2018-11-03 22:58 UTC, ErwanAliasr1 commented on cmd/main.go
> + * Ceph Nano (C) 2017 Red Hat, Inc.
One more

2018-11-03 22:58 UTC, ErwanAliasr1 commented on cmd/purge.go
> + * Ceph Nano (C) 2017 Red Hat, Inc.
Oh !

2018-11-03 22:58 UTC, ErwanAliasr1 commented on cmd/stop.go
> + * Ceph Nano (C) 2017 Red Hat, Inc.
+1

2018-11-03 22:59 UTC, ErwanAliasr1 requested changes

2018-11-03 22:59 UTC, ErwanAliasr1 commented on cmd/image_list.go
> +	envRegistry := os.Getenv("CN_REGISTRY")
We may avoid create a variable if that is used once

2018-11-03 22:59 UTC, ErwanAliasr1 commented on cmd/main.go
> +	envRegistry := os.Getenv("CN_REGISTRY")
ditto

2018-11-05 10:45 UTC, leseb commented
@ErwanAliasr1 comments have been addressed

2018-11-05 16:21 UTC, ErwanAliasr1 approved these changes

2018-11-05 16:21 UTC, merged